[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ceveri"
authors = [{name = "Arda Uzunoğlu", email = "ardauzunogluarda@gnail.com"}]
dynamic = ["version", "description"]
