[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ÇeVeri"
authors = [{name = "Arda Uzunoğlu", email = "ardauzunogluarda@gmail.com"}]
dynamic = ["version", "description"]
